spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_app
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration
